uint8 UNIT_NORMALIZED=1
uint8 UNIT_RADIANS=2

uint8 position_unit
string[] joint_names
float64[] positions
float64 speed_scaling
float64 max_effort
bool stop_on_contact
builtin_interfaces/Duration timeout
---
bool success
zzx_interfaces/ErrorStatus error
zzx_interfaces/ExecutionStatus execution
float64[] final_positions
bool contact_detected
---
zzx_interfaces/ExecutionStatus execution
float64[] current_positions
bool contact_detected
