zzx_interfaces/TaskCommand command
---
bool success
zzx_interfaces/ErrorStatus error
zzx_interfaces/ExecutionStatus execution
builtin_interfaces/Duration elapsed_time
---
zzx_interfaces/ExecutionStatus execution
uint32 current_step
uint32 total_steps
